preprocessing:
  working_directory: STDL_Classifier
  inputs:
    polygon_src: ./data/sources/gt_matching_roofs.gpkg
    rasters_dir: ./data/sources/scratch_dataset
    class_labels_dir: ./data/sources/class_labels_multi.csv
  outputs:
    output_dir: data/dataset
  processes:
    image_norm_style: stretching
    do_rangelimit: false
    do_mask: false
    do_smooth_mask: false
    do_da_rotation: true
    do_da_flipping: false
    do_drop_overlapping: false
    do_drop_based_on_ndvi: true
    do_drop_small_samples: false
    do_global_stats: false
  metadata:
    sample_size: 512
    rangelimit_mode: none
    rangelimit_threshold: 10000
    epsg: 2056
    sample_size_threshold: 5000
  multiprocessing:
    max_workers: 0
  security:
    do_abort: false
training:
  inputs:
    dataset_root: data/dataset
  outputs:
    res_dir: results/trainings/
    folder_name_suffix: smoothing_label
  processes:
    do_preprocessing: true
  parameters:
    norm_boundaries:
    - - 0
      - 255
    - - 0
      - 255
    - - 0
      - 255
    - - 0
      - 255
    - - -1
      - 1
    - - 0
      - 765
    data_frac: 1.0
    train_frac: 0.7
    num_epochs: 100
    batch_size: 16
    num_workers: 8
    learning_rate: 0.0001
    weight_decay: 0.0001
    from_pretrained: false
  training_mode: single
  model:
    model_type: multi
    backbone: convslayers
    backbone_num_levels: 3
    backbone_num_layers: 1
    aspp_atrous_rates:
    - 4
    - 8
    - 12
    dropout_frac: 0.0
    model_src: src/models/DeepLabV3Classificator.py
