inference:
  working_directory: D:/GitHubProjects/proj-vegroofs-DL
  inputs:
    polygon_src: data\sources\example\polygons\roofs_example.gpkg
    rasters_dir: data\sources\example\rasters
    chm_src : data\sources\example\polygons\chm_example.gpkg
    class_labels_dir: data\sources\class_labels_multi.csv
    model_src: models\inference\model_multi.tar
  outputs:
    dataset_dir: data/inference/dataset
    preds_dir: results/inferences
    folder_name_suffix: test
  processes:
    do_preprocessing: False
  parameters:
    data_frac: 1.0
    mode: multi
  preprocess_overright:
    processes:
      do_drop_overlapping: False
      do_drop_based_on_ndvi: False
    metadata:
      batch_size: 0
      sample_size: 1024
    multi_processing:
      max_workers: 0
  train_overright:
    norm_boundaries: [[0,255],[0,255],[0,255],[0,255],[-1,1],[0,765]]
    batch_size: 4
    num_workers: 4
    backbone_num_levels: 3
    backbone_num_layers: 1
    aspp_atrous_rates: [4, 8, 12] 