inference:
  working_directory: D:/GitHubProjects/STDL_Classifier_new
  inputs:
    polygon_src: ./data/inference/infs_concat_roofs_join_green.gpkg
    rasters_dir: ./data/inference/tiles_inference
    class_labels_dir: ./data/sources/class_labels_multi.csv
    model_src: ./models/inference/model.tar
  outputs:
    dataset_dir: ./data/inference/dataset
    preds_dir: ./results/inferences
    folder_name_suffix: test
  processes:
    do_preprocessing: True
  parameters:
    data_frac: 1.0
    mode: multi
  preprocess_overright:
    processes:
      do_drop_overlapping: False
      do_drop_based_on_ndvi: False
    metadata:
      batch_size: 500
      sample_size: 512
      rangelimit_mode: none
      rangelimit_threshold: 10000
    multi_processing:
      max_workers: 0
  train_overright:
    norm_boundaries: [[0,255],[0,255],[0,255],[0,255],[-1,1],[0,765]]
    batch_size: 16
    num_workers: 8
    backbone_num_levels: 3
    backbone_num_layers: 1
    aspp_atrous_rates: [4, 8, 12] 