preprocessing:
  working_directory: D:/GitHubProjects/STDL_Classifier_test_2/proj_vegroofs_dl
  inputs:
    polygon_src: data/sources/gt_matching_roofs.gpkg
    rasters_dir: data/sources/scratch_dataset
    class_labels_dir: data/sources/class_labels_multi.csv
  outputs:
    output_dir: data/dataset_test
  processes:
    image_norm_style: stretching  # one of {'stretching', 'padding'}
    do_da_rotation: True
    do_da_flipping: True
    do_drop_overlapping: False
    do_drop_based_on_ndvi: True
    do_produce_tif: True
  metadata:
    preprocess_mode: training  # choose in {'training', 'inference'}
    batch_size: 0   # if 0, load everything at once
    sample_size: 512  # 128 and higher
    epsg: 2056
  multiprocessing:
    max_workers: 0 # if 0, uses all the available cores but might overload the RAM
  security:
    do_abort: False