preprocessing:
  working_directory: D:/GitHubProjects/proj-vegroofs-DL
  inputs:
    polygon_src: data\sources\example\polygons\roofs_example.gpkg
    rasters_dir: data\sources\example\rasters
    chm_src : data\sources\example\polygons\chm_example.gpkg
    class_labels_dir: data\sources\class_labels_multi.csv
  outputs:
    output_dir: data/dataset_test
  processes:
    image_norm_style: stretching  # one of {'stretching', 'padding'}
    do_da_rotation: True
    do_da_flipping: True
    do_drop_overlapping: False
    do_drop_based_on_ndvi: True
    do_produce_tif: True
  metadata:
    preprocess_mode: training  # choose in {'training', 'inference'}
    batch_size: 0   # if 0, load everything at once
    sample_size: 128  # 128 and higher
    epsg: 2056
  multiprocessing:
    max_workers: 0 # if 0, uses all the available cores but might overload the RAM
  security:
    do_abort: False